In [ ]:
# import libraries
import pandas as pd

In [ ]:
# import spotify

!pip install spotipy pandas

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

Requirement already satisfied: spotipy in /usr/local/lib/python3.10/dist-packages (2.23.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: redis>=3.5.3 in /usr/local/lib/python3.10/dist-packages (from spotipy) (4.6.0)
Requirement already satisfied: requests>=2.25.0 in /usr/local/lib/python3.10/dist-packages (from spotipy) (2.27.1)
Requirement already satisfied: six>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from spotipy) (1.16.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.10/dist-packages (from spotipy) (1.26.16)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: async-timeout>=4.0.2 in /usr/local/lib/python3.10/dist-packages (from redis>=3.5.3->spotipy) (4.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.25.0->spotipy) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.25.0->spotipy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.25.0->spotipy) (3.4)

In [ ]:
client_id = '775e603decf1454299111cabaa0727a1'
client_secret = 'effe2a61ec83412e9313d68fd6a07c6b'

In [ ]:
# Initialize the Spotify API client

sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id=client_id, client_secret=client_secret))

In [ ]:
# playlist of top songs from 10 years 2013 to 2022
# there are some songs here which repeat across year - do we include multiple entries?

playlist_urls = {
    2013: 'https://open.spotify.com/playlist/37i9dQZF1DX3Sp0P28SIer', #100 songs
    2014: 'https://open.spotify.com/playlist/37i9dQZF1DX0h0QnLkMBl4', #100 songs
    2015: 'https://open.spotify.com/playlist/37i9dQZF1DX9ukdrXQLJGZ?si=17aa4b3e603d426b', #100 songs
    2016: 'https://open.spotify.com/playlist/37i9dQZF1DX8XZ6AUo9R4R?si=93d023c9de3f42f3', #130 songs
    2017: 'https://open.spotify.com/playlist/37i9dQZF1DWTE7dVUebpUW?si=0b7d5eb26427433a', #100 songs
    2018: 'https://open.spotify.com/playlist/37i9dQZF1DXe2bobNYDtW8?si=6c0a3c1635174dd6', #100 songs
    2019: 'https://open.spotify.com/playlist/37i9dQZF1DWVRSukIED0e9?si=c06f704b3efd4839', #100 songs
    2020: 'https://open.spotify.com/playlist/2fmTTbBkXi8pewbUvG3CeZ', #135 songs (unofficial playlist)
    2021: 'https://open.spotify.com/playlist/5GhQiRkGuqzpWZSE7OU4Se', #100 songs (unofficial playlist)
    2022: 'https://open.spotify.com/playlist/56r5qRUv3jSxADdmBkhcz7' #100 songs (unofficial playlist)
}

In [ ]:
# extract the top 100 songs from a Spotify playlist URL

def get_top_100_songs_from_playlist(playlist_url):
    results = sp.playlist_tracks(playlist_url, limit=100)
    top_songs = results['items']
    return top_songs

In [ ]:
# retrieve the audio features for a given track

def get_audio_features(track_id):
    audio_features = sp.audio_features(track_id)[0]
    return audio_features

In [ ]:
# List of audio feature names to extract
audio_features_list = [
    'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
    'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms', 'time_signature']

In [ ]:
# Loop over the playlist URLs, retrieve the top 100 songs for each playlist, and collect their audio features

data = []

# Loop through the dictionary, retrieve the top 100 songs for each playlist URL, and collect their audio features
for year, playlist_url in playlist_urls.items():
    top_songs = get_top_100_songs_from_playlist(playlist_url)
    for song in top_songs:
        track_name = song['track']['name']
        artist_name = song['track']['artists'][0]['name']
        #other possibilities
        #genre = song['track']['artists'][0]['followers'] *returns an array and artist may not be classified
        #followers = song['track']['artists'][0]['followers']['total']
        track_id = song['track']['id']
        audio_features = get_audio_features(track_id)

        if audio_features:
            # Extract specific audio features and store them as separate columns
            audio_feature_values = {feature: audio_features[feature] for feature in audio_features_list}
            data.append({
                'year': year,
                'track_name': track_name,
                'artist_name': artist_name,
                'track_id': track_id,
                **audio_feature_values
            })

In [ ]:
# labelling these songs as hits
df = pd.DataFrame(data)
df['hit'] = 1
df

,year,track_name,artist_name,track_id,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,hit
0,2013,Mirrors,Justin Timberlake,4rHZZAmHpZrA3iH5zx8frV,0.574,0.512,5,-6.664,0,0.0503,0.23400,0.000000,0.0946,0.512,76.899,484147,4,1
1,2013,Blurred Lines,Robin Thicke,5PUvinSo4MNqW7vmomGRS7,0.861,0.504,7,-7.707,1,0.0489,0.00412,0.000018,0.0783,0.881,120.000,263053,4,1
2,2013,Radioactive,Imagine Dragons,4G8gkOterJn0Ywt6uhqbhp,0.448,0.784,9,-3.686,1,0.0627,0.10600,0.000108,0.6680,0.236,136.245,186813,4,1
3,2013,Wake Me Up,Avicii,0nrRP2bk19rLc0orkWPQk2,0.532,0.783,2,-5.697,1,0.0523,0.00380,0.001200,0.1610,0.643,124.080,247427,4,1
4,2013,Another Love,Tom Odell,3JvKfv6T31zO0ini8iNItO,0.445,0.537,4,-8.532,0,0.0400,0.69500,0.000017,0.0944,0.131,122.769,244360,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2022,Die Hard,Kendrick Lamar,2g6tReTlM2Akp41g0HaeXN,0.775,0.736,1,-8.072,0,0.2470,0.31900,0.001160,0.1270,0.362,100.988,239027,4,1
996,2022,Big Energy,Latto,4pi1G1x8tl9VfdD9bL3maT,0.937,0.793,11,-4.431,0,0.1150,0.04530,0.000000,0.3410,0.794,106.022,172540,4,1
997,2022,Doja,Central Cee,3LtpKP5abr2qqjunvjlX5i,0.911,0.573,6,-7.430,1,0.2880,0.38000,0.000000,0.4030,0.972,140.040,97393,4,1
998,2022,pushin P (feat. Young Thug),Gunna,3XOalgusokruzA5ZBA2Qcb,0.773,0.422,1,-4.572,0,0.1870,0.00783,0.006930,0.1290,0.488,77.502,136267,1,1
999,2022,Thousand Miles,The Kid LAROI,1r8ZCjfrQxoy2wVaBUbpwg,0.376,0.657,7,-4.658,1,0.0768,0.08580,0.000000,0.0884,0.203,80.565,164782,4,1

In [ ]:
df = df.drop_duplicates(subset="track_id", keep="first", inplace=False)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 954 entries, 0 to 999
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              954 non-null    int64
 1   track_name        954 non-null    object
 2   artist_name       954 non-null    object
 3   track_id          954 non-null    object
 4   danceability      954 non-null    float64
 5   energy            954 non-null    float64
 6   key               954 non-null    int64
 7   loudness          954 non-null    float64
 8   mode              954 non-null    int64
 9   speechiness       954 non-null    float64
 10  acousticness      954 non-null    float64
 11  instrumentalness  954 non-null    float64
 12  liveness          954 non-null    float64
 13  valence           954 non-null    float64
 14  tempo             954 non-null    float64
 15  duration_ms       954 non-null    int64
 16  time_signature    954 non-null    int64
 17  hit               954 non-null    int64
dtypes: float64(9), int64(6), object(3)
memory usage: 141.6+ KB

In [ ]:
# mount google drive to dump data (not sure if this will work for you)
from google.colab import drive
drive.mount("/content/gdrive", force_remount=True)

data_dir_path='/content/gdrive/My Drive/NYP ML PROJECT/Data/'

Mounted at /content/gdrive

In [ ]:
import os

directory_path = '/content/gdrive/'

if os.path.exists(directory_path):
    print("The directory exists.")
else:
    print("The directory does not exist.")

The directory exists.

In [ ]:
# save df as a CSV file

path = data_dir_path + 'spotify_top_songs_audio_features.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df.to_csv(f)

In [ ]:
# import the million songs data set
file_path = data_dir_path + 'spotify_million_songs.csv'

# Read the CSV file into a DataFrame
spotify_million = pd.read_csv(file_path)

In [ ]:
spotify_million.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1159764 entries, 0 to 1159763
Data columns (total 20 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Unnamed: 0        1159764 non-null  int64
 1   artist_name       1159764 non-null  object
 2   track_name        1159764 non-null  object
 3   track_id          1159764 non-null  object
 4   popularity        1159764 non-null  int64
 5   year              1159764 non-null  int64
 6   genre             1159764 non-null  object
 7   danceability      1159764 non-null  float64
 8   energy            1159764 non-null  float64
 9   key               1159764 non-null  int64
 10  loudness          1159764 non-null  float64
 11  mode              1159764 non-null  int64
 12  speechiness       1159764 non-null  float64
 13  acousticness      1159764 non-null  float64
 14  instrumentalness  1159764 non-null  float64
 15  liveness          1159764 non-null  float64
 16  valence           1159764 non-null  float64
 17  tempo             1159764 non-null  float64
 18  duration_ms       1159764 non-null  int64
 19  time_signature    1159764 non-null  int64
dtypes: float64(9), int64(7), object(4)
memory usage: 177.0+ MB

In [ ]:
year_counts = spotify_million['year'].value_counts().sort_index(ascending=False)
year_counts

2023    38649
2022    53692
2021    53566
2020    55066
2019    55793
2018    56572
2017    56241
2016    40273
2015    51607
2014    53179
2013    53216
2012    54797
2011    46444
2010    46868
2009    46869
2008    47432
2007    46001
2006    45474
2005    43780
2004    43390
2003    42368
2002    42102
2001    42351
2000    44034
Name: year, dtype: int64

In [ ]:
spotify_million.drop(['Unnamed: 0', 'popularity', 'genre'], axis=1, inplace=True)

In [ ]:
spotify_million = spotify_million[(spotify_million.year < 2023) & (spotify_million.year > 2012)]
spotify_million.head()

,artist_name,track_name,track_id,year,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
54797,Sara Bareilles,Brave,6Uy6K3KdmUdAfelUp0SeXn,2013,0.551,0.836,10,-3.838,0,0.0524,0.00502,0.000021,0.0425,0.758,185.063,220573,4
54798,Drew Holcomb & The Neighbors,What Would I Do Without You,11TK5KLtLZUdKr1C549bAw,2013,0.602,0.336,8,-11.106,1,0.0369,0.88300,0.001700,0.1430,0.335,90.894,172213,4
54799,Sara Bareilles,I Choose You,7jJH8F3PHlNvxfqEAAfFDl,2013,0.731,0.572,6,-7.889,0,0.0445,0.10500,0.000120,0.1330,0.947,154.038,218573,4
54800,Ben Rector,I Like You,7Afr3PKTtlFGHGiXYgnv6P,2013,0.624,0.334,3,-11.890,1,0.0391,0.32100,0.000003,0.1130,0.397,157.920,138507,4
54801,Five For Fighting,Heaven Knows,0qJGlogD7AyMLAJfQ42aI2,2013,0.600,0.845,10,-7.076,1,0.0311,0.04800,0.000000,0.2400,0.392,97.631,210612,4

In [ ]:
#selecting random songs from the data set without duplicating the hits

import random

# get the list of track IDs from df
other_track_ids = df['track_id'].tolist()

# initialize an empty list to store the randomly selected songs
random_track_ids = []

# group spotify_million by 'year'
grouped_by_year = spotify_million.groupby('year')

# randomly select 500 songs from each year without overlap
num_songs_per_year = 500

for year, group in grouped_by_year:
    available_track_ids = [track_id for track_id in group['track_id'].tolist() if track_id not in other_track_ids]
    selected_track_ids = random.sample(available_track_ids, min(num_songs_per_year, len(available_track_ids)))
    random_track_ids.extend(selected_track_ids)
    other_track_ids.extend(selected_track_ids)

In [ ]:
spotify_million_sample = spotify_million[spotify_million['track_id'].isin(random_track_ids)].copy()

In [ ]:
# to check if there are any duplicate songs in the two datasets
check_id = spotify_million_sample['track_id'].tolist()
duplicate_songs = df[df['track_id'].isin(check_id)]
duplicate_songs

Empty DataFrame
Columns: [year, track_name, artist_name, track_id, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, duration_ms, time_signature, hit]
Index: []

In [ ]:
# assigning value of 0 to non-hits

spotify_million_sample['hit'] = 0
spotify_million_sample

,artist_name,track_name,track_id,year,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,hit
54802,The Civil Wars,Devil’s Backbone,1XTp9AoHDoCQMmMWH0ch8M,2013,0.337,0.341,4,-10.123,0,0.0348,0.8540,0.000076,0.2410,0.348,114.538,149000,4,0
55230,Five For Fighting,I Don’t Want Your Love,7u42KKgSdQWBYePbaNjR6S,2013,0.444,0.296,11,-9.219,1,0.0308,0.9010,0.000002,0.1560,0.242,76.965,214633,4,0
55292,Green River Ordinance,Fool for You,0dOA8BozMVkn3pFLyJ7r6n,2013,0.467,0.567,5,-8.893,1,0.0302,0.0502,0.000376,0.1310,0.340,144.688,259147,4,0
55404,Diane Birch,Speak a Little Louder,6Tu6AYz9j6EcnGtOs2dxDk,2013,0.553,0.514,8,-7.287,1,0.0284,0.0602,0.010600,0.1210,0.331,76.507,226213,4,0
55583,Donovan Raitt,I Heard the Voice of Jesus Say,7lNVShUDPCknSkFgdXAYQ1,2013,0.625,0.296,4,-14.360,0,0.0689,0.8950,0.944000,0.1100,0.416,75.203,187600,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583599,DJ Nu-Mark,Huh Huh,4AzdzPQnO5kTqcEkYlC98Z,2022,0.897,0.824,5,-6.053,0,0.0480,0.0895,0.914000,0.2320,0.889,150.101,109192,4,0
583627,GusGus,Hold Me In Your Arms Again,3fX9OkJuoRWFoMmIU8IFzf,2022,0.643,0.837,1,-8.492,1,0.0461,0.0360,0.383000,0.0753,0.573,118.008,393907,4,0
583635,Federico Aubele,Pink Spray Painted Clouds,0luxcIWWsaZLD4SzoNNMrJ,2022,0.745,0.425,0,-9.185,1,0.0303,0.8090,0.661000,0.1740,0.565,114.046,153684,4,0
583651,Doctor Flake,Free at last ?,5MXKWQ2kaBqxHlrpd4797h,2022,0.595,0.704,7,-9.803,1,0.0444,0.2270,0.914000,0.0803,0.803,100.013,504184,4,0
583915,Vadim,Higher,1atrbuO1B2ckOr652vTh6z,2022,0.610,0.203,4,-14.801,0,0.0370,0.9600,0.136000,0.1010,0.220,119.922,225008,4,0

In [ ]:
# concatenating the two dataframes
spotify_million_sample = spotify_million_sample.reindex(columns=df.columns)
spotify_million_sample.head()
df_prepped = pd.concat([df, spotify_million_sample])

In [ ]:
df_prepped

,year,track_name,artist_name,track_id,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,hit
0,2013,Mirrors,Justin Timberlake,4rHZZAmHpZrA3iH5zx8frV,0.574,0.512,5,-6.664,0,0.0503,0.23400,0.000000,0.0946,0.512,76.899,484147,4,1
1,2013,Blurred Lines,Robin Thicke,5PUvinSo4MNqW7vmomGRS7,0.861,0.504,7,-7.707,1,0.0489,0.00412,0.000018,0.0783,0.881,120.000,263053,4,1
2,2013,Radioactive,Imagine Dragons,4G8gkOterJn0Ywt6uhqbhp,0.448,0.784,9,-3.686,1,0.0627,0.10600,0.000108,0.6680,0.236,136.245,186813,4,1
3,2013,Wake Me Up,Avicii,0nrRP2bk19rLc0orkWPQk2,0.532,0.783,2,-5.697,1,0.0523,0.00380,0.001200,0.1610,0.643,124.080,247427,4,1
4,2013,Another Love,Tom Odell,3JvKfv6T31zO0ini8iNItO,0.445,0.537,4,-8.532,0,0.0400,0.69500,0.000017,0.0944,0.131,122.769,244360,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583599,2022,Huh Huh,DJ Nu-Mark,4AzdzPQnO5kTqcEkYlC98Z,0.897,0.824,5,-6.053,0,0.0480,0.08950,0.914000,0.2320,0.889,150.101,109192,4,0
583627,2022,Hold Me In Your Arms Again,GusGus,3fX9OkJuoRWFoMmIU8IFzf,0.643,0.837,1,-8.492,1,0.0461,0.03600,0.383000,0.0753,0.573,118.008,393907,4,0
583635,2022,Pink Spray Painted Clouds,Federico Aubele,0luxcIWWsaZLD4SzoNNMrJ,0.745,0.425,0,-9.185,1,0.0303,0.80900,0.661000,0.1740,0.565,114.046,153684,4,0
583651,2022,Free at last ?,Doctor Flake,5MXKWQ2kaBqxHlrpd4797h,0.595,0.704,7,-9.803,1,0.0444,0.22700,0.914000,0.0803,0.803,100.013,504184,4,0
583915,2022,Higher,Vadim,1atrbuO1B2ckOr652vTh6z,0.610,0.203,4,-14.801,0,0.0370,0.96000,0.136000,0.1010,0.220,119.922,225008,4,0

In [ ]:
path = data_dir_path + 'data_prepped.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_prepped.to_csv(f,index=False)

In [ ]:
duplicates = df_prepped.duplicated(subset='track_id', keep=False)
duplicate_rows = df_prepped[duplicates]
duplicate_rows

Empty DataFrame
Columns: [year, track_name, artist_name, track_id, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, duration_ms, time_signature, hit]
Index: []